<?php
/**
 * AclsMetaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud_User_API
 *
 * FileCloud HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AclsMetaTest Class Doc Comment
 *
 * @category    Class
 * @description AclsMeta
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AclsMetaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AclsMeta"
     */
    public function testAclsMeta()
    {
    }

    /**
     * Test attribute "aclid"
     */
    public function testPropertyAclid()
    {
    }

    /**
     * Test attribute "createddate"
     */
    public function testPropertyCreateddate()
    {
    }

    /**
     * Test attribute "createdts"
     */
    public function testPropertyCreatedts()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "inherit"
     */
    public function testPropertyInherit()
    {
    }

    /**
     * Test attribute "usercount"
     */
    public function testPropertyUsercount()
    {
    }

    /**
     * Test attribute "groupcount"
     */
    public function testPropertyGroupcount()
    {
    }
}
