<?php
/**
 * AuthenticationinfoInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud_User_API
 *
 * FileCloud HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuthenticationinfoInfoTest Class Doc Comment
 *
 * @category    Class
 * @description AuthenticationinfoInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthenticationinfoInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthenticationinfoInfo"
     */
    public function testAuthenticationinfoInfo()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "displayname"
     */
    public function testPropertyDisplayname()
    {
    }

    /**
     * Test attribute "peerid"
     */
    public function testPropertyPeerid()
    {
    }

    /**
     * Test attribute "authenticated"
     */
    public function testPropertyAuthenticated()
    {
    }

    /**
     * Test attribute "isguestauthenticated"
     */
    public function testPropertyIsguestauthenticated()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "guesthash"
     */
    public function testPropertyGuesthash()
    {
    }

    /**
     * Test attribute "guesthashurl"
     */
    public function testPropertyGuesthashurl()
    {
    }

    /**
     * Test attribute "isremote"
     */
    public function testPropertyIsremote()
    {
    }

    /**
     * Test attribute "reasoncode"
     */
    public function testPropertyReasoncode()
    {
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
    }

    /**
     * Test attribute "authtype"
     */
    public function testPropertyAuthtype()
    {
    }

    /**
     * Test attribute "enablesaml"
     */
    public function testPropertyEnablesaml()
    {
    }

    /**
     * Test attribute "userlevel"
     */
    public function testPropertyUserlevel()
    {
    }

    /**
     * Test attribute "userauthtype"
     */
    public function testPropertyUserauthtype()
    {
    }
}
