<?php
/**
 * GetAuthenticationInfoResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud API
 *
 * The FileCloud APIs provide developers with the tools necessary to build a variety of apps and clients. This allows extensibility and integration of FileCloud with your existing enterprise systems and frameworks. FileCloud developer API is simple to use and integrate.
 *
 * OpenAPI spec version: 14.0.0.34184
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetAuthenticationInfoResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetAuthenticationInfoResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetAuthenticationInfoResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetAuthenticationInfoResponse"
     */
    public function testGetAuthenticationInfoResponse()
    {

    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {

    }

    /**
     * Test attribute "displayname"
     */
    public function testPropertyDisplayname()
    {

    }

    /**
     * Test attribute "peerid"
     */
    public function testPropertyPeerid()
    {

    }

    /**
     * Test attribute "authenticated"
     */
    public function testPropertyAuthenticated()
    {

    }

    /**
     * Test attribute "isguestauthenticated"
     */
    public function testPropertyIsguestauthenticated()
    {

    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {

    }

    /**
     * Test attribute "guesthash"
     */
    public function testPropertyGuesthash()
    {

    }

    /**
     * Test attribute "guesthashurl"
     */
    public function testPropertyGuesthashurl()
    {

    }

    /**
     * Test attribute "isremote"
     */
    public function testPropertyIsremote()
    {

    }

    /**
     * Test attribute "reasoncode"
     */
    public function testPropertyReasoncode()
    {

    }

    /**
     * Test attribute "oS"
     */
    public function testPropertyOS()
    {

    }

    /**
     * Test attribute "authtype"
     */
    public function testPropertyAuthtype()
    {

    }

    /**
     * Test attribute "enablesaml"
     */
    public function testPropertyEnablesaml()
    {

    }

    /**
     * Test attribute "userlevel"
     */
    public function testPropertyUserlevel()
    {

    }

    /**
     * Test attribute "userauthtype"
     */
    public function testPropertyUserauthtype()
    {

    }

}
