<?php
/**
 * GetfilelistResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud API
 *
 * The FileCloud APIs provide developers with the tools necessary to build a variety of apps and clients. This allows extensibility and integration of FileCloud with your existing enterprise systems and frameworks. FileCloud developer API is simple to use and integrate.
 *
 * OpenAPI spec version: 14.0.0.34184
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetfilelistResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetfilelistResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetfilelistResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetfilelistResponse"
     */
    public function testGetfilelistResponse()
    {

    }

    /**
     * Test attribute "parentpath"
     */
    public function testPropertyParentpath()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "realpath"
     */
    public function testPropertyRealpath()
    {

    }

    /**
     * Test attribute "canupload"
     */
    public function testPropertyCanupload()
    {

    }

    /**
     * Test attribute "isshareable"
     */
    public function testPropertyIsshareable()
    {

    }

    /**
     * Test attribute "candownload"
     */
    public function testPropertyCandownload()
    {

    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {

    }

    /**
     * Test attribute "dirpath"
     */
    public function testPropertyDirpath()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "ext"
     */
    public function testPropertyExt()
    {

    }

    /**
     * Test attribute "fullsize"
     */
    public function testPropertyFullsize()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "fullfilename"
     */
    public function testPropertyFullfilename()
    {

    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {

    }

    /**
     * Test attribute "modifiedpoch"
     */
    public function testPropertyModifiedpoch()
    {

    }

    /**
     * Test attribute "isroot"
     */
    public function testPropertyIsroot()
    {

    }

    /**
     * Test attribute "issyncable"
     */
    public function testPropertyIssyncable()
    {

    }

    /**
     * Test attribute "isshared"
     */
    public function testPropertyIsshared()
    {

    }

    /**
     * Test attribute "canrename"
     */
    public function testPropertyCanrename()
    {

    }

    /**
     * Test attribute "showprev"
     */
    public function testPropertyShowprev()
    {

    }

    /**
     * Test attribute "canfavorite"
     */
    public function testPropertyCanfavorite()
    {

    }

    /**
     * Test attribute "favoritelist"
     */
    public function testPropertyFavoritelist()
    {

    }

    /**
     * Test attribute "favoriteid"
     */
    public function testPropertyFavoriteid()
    {

    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {

    }

}
