<?php
/**
 * GetprofilesettingsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud API
 *
 * The FileCloud APIs provide developers with the tools necessary to build a variety of apps and clients. This allows extensibility and integration of FileCloud with your existing enterprise systems and frameworks. FileCloud developer API is simple to use and integrate.
 *
 * OpenAPI spec version: 18.1.0.682
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetprofilesettingsResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetprofilesettingsResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetprofilesettingsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetprofilesettingsResponse"
     */
    public function testGetprofilesettingsResponse()
    {
    }

    /**
     * Test attribute "nickname"
     */
    public function testPropertyNickname()
    {
    }

    /**
     * Test attribute "peerid"
     */
    public function testPropertyPeerid()
    {
    }

    /**
     * Test attribute "profileroot"
     */
    public function testPropertyProfileroot()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "displayname"
     */
    public function testPropertyDisplayname()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "secretqn"
     */
    public function testPropertySecretqn()
    {
    }

    /**
     * Test attribute "secretans"
     */
    public function testPropertySecretans()
    {
    }

    /**
     * Test attribute "hint"
     */
    public function testPropertyHint()
    {
    }

    /**
     * Test attribute "dateformat"
     */
    public function testPropertyDateformat()
    {
    }

    /**
     * Test attribute "isremote"
     */
    public function testPropertyIsremote()
    {
    }

    /**
     * Test attribute "profileuserdatadir"
     */
    public function testPropertyProfileuserdatadir()
    {
    }

    /**
     * Test attribute "emailverifytag"
     */
    public function testPropertyEmailverifytag()
    {
    }
}
