<?php
/**
 * GetshareforpathResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud API
 *
 * The FileCloud APIs provide developers with the tools necessary to build a variety of apps and clients. This allows extensibility and integration of FileCloud with your existing enterprise systems and frameworks. FileCloud developer API is simple to use and integrate.
 *
 * OpenAPI spec version: 18.1.0.682
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetshareforpathResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetshareforpathResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetshareforpathResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetshareforpathResponse"
     */
    public function testGetshareforpathResponse()
    {
    }

    /**
     * Test attribute "shareid"
     */
    public function testPropertyShareid()
    {
    }

    /**
     * Test attribute "sharename"
     */
    public function testPropertySharename()
    {
    }

    /**
     * Test attribute "sharelocation"
     */
    public function testPropertySharelocation()
    {
    }

    /**
     * Test attribute "shareurl"
     */
    public function testPropertyShareurl()
    {
    }

    /**
     * Test attribute "viewmode"
     */
    public function testPropertyViewmode()
    {
    }

    /**
     * Test attribute "validityperiod"
     */
    public function testPropertyValidityperiod()
    {
    }

    /**
     * Test attribute "sharesizelimit"
     */
    public function testPropertySharesizelimit()
    {
    }

    /**
     * Test attribute "maxdownloads"
     */
    public function testPropertyMaxdownloads()
    {
    }

    /**
     * Test attribute "downloadcount"
     */
    public function testPropertyDownloadcount()
    {
    }

    /**
     * Test attribute "viewsize"
     */
    public function testPropertyViewsize()
    {
    }

    /**
     * Test attribute "thumbsize"
     */
    public function testPropertyThumbsize()
    {
    }

    /**
     * Test attribute "allowpublicaccess"
     */
    public function testPropertyAllowpublicaccess()
    {
    }

    /**
     * Test attribute "allowpublicupload"
     */
    public function testPropertyAllowpublicupload()
    {
    }

    /**
     * Test attribute "allowpublicviewonly"
     */
    public function testPropertyAllowpublicviewonly()
    {
    }

    /**
     * Test attribute "allowpublicuploadonly"
     */
    public function testPropertyAllowpublicuploadonly()
    {
    }

    /**
     * Test attribute "isdir"
     */
    public function testPropertyIsdir()
    {
    }

    /**
     * Test attribute "isvalid"
     */
    public function testPropertyIsvalid()
    {
    }

    /**
     * Test attribute "createddate"
     */
    public function testPropertyCreateddate()
    {
    }

    /**
     * Test attribute "allowedit"
     */
    public function testPropertyAllowedit()
    {
    }

    /**
     * Test attribute "allowdelete"
     */
    public function testPropertyAllowdelete()
    {
    }

    /**
     * Test attribute "allowsync"
     */
    public function testPropertyAllowsync()
    {
    }

    /**
     * Test attribute "allowshare"
     */
    public function testPropertyAllowshare()
    {
    }

    /**
     * Test attribute "shareowner"
     */
    public function testPropertyShareowner()
    {
    }

    /**
     * Test attribute "hidenotification"
     */
    public function testPropertyHidenotification()
    {
    }

    /**
     * Test attribute "ispublicsecure"
     */
    public function testPropertyIspublicsecure()
    {
    }
}
