<?php
/**
 * RmcClientsRmcClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud_User_API
 *
 * FileCloud HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RmcClientsRmcClientTest Class Doc Comment
 *
 * @category    Class
 * @description RmcClientsRmcClient
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RmcClientsRmcClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RmcClientsRmcClient"
     */
    public function testRmcClientsRmcClient()
    {
    }

    /**
     * Test attribute "rid"
     */
    public function testPropertyRid()
    {
    }

    /**
     * Test attribute "remote_client_id"
     */
    public function testPropertyRemoteClientId()
    {
    }

    /**
     * Test attribute "remote_client_api_level"
     */
    public function testPropertyRemoteClientApiLevel()
    {
    }

    /**
     * Test attribute "remote_client_disp_name"
     */
    public function testPropertyRemoteClientDispName()
    {
    }

    /**
     * Test attribute "remote_client_os_type"
     */
    public function testPropertyRemoteClientOsType()
    {
    }

    /**
     * Test attribute "remote_client_app_version"
     */
    public function testPropertyRemoteClientAppVersion()
    {
    }

    /**
     * Test attribute "remote_client_os_version"
     */
    public function testPropertyRemoteClientOsVersion()
    {
    }

    /**
     * Test attribute "isblocked"
     */
    public function testPropertyIsblocked()
    {
    }

    /**
     * Test attribute "remote_client_last_login"
     */
    public function testPropertyRemoteClientLastLogin()
    {
    }

    /**
     * Test attribute "userid"
     */
    public function testPropertyUserid()
    {
    }

    /**
     * Test attribute "pending_actions_count"
     */
    public function testPropertyPendingActionsCount()
    {
    }

    /**
     * Test attribute "remote_client_status"
     */
    public function testPropertyRemoteClientStatus()
    {
    }

    /**
     * Test attribute "server_code"
     */
    public function testPropertyServerCode()
    {
    }
}
