<?php
/**
 * SharesShareTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud_User_API
 *
 * FileCloud HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SharesShareTest Class Doc Comment
 *
 * @category    Class
 * @description SharesShare
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SharesShareTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SharesShare"
     */
    public function testSharesShare()
    {
    }

    /**
     * Test attribute "shareid"
     */
    public function testPropertyShareid()
    {
    }

    /**
     * Test attribute "sharename"
     */
    public function testPropertySharename()
    {
    }

    /**
     * Test attribute "sharelocation"
     */
    public function testPropertySharelocation()
    {
    }

    /**
     * Test attribute "readablelocation"
     */
    public function testPropertyReadablelocation()
    {
    }

    /**
     * Test attribute "shareurl"
     */
    public function testPropertyShareurl()
    {
    }

    /**
     * Test attribute "viewmode"
     */
    public function testPropertyViewmode()
    {
    }

    /**
     * Test attribute "validityperiod"
     */
    public function testPropertyValidityperiod()
    {
    }

    /**
     * Test attribute "sharesizelimit"
     */
    public function testPropertySharesizelimit()
    {
    }

    /**
     * Test attribute "maxdownloads"
     */
    public function testPropertyMaxdownloads()
    {
    }

    /**
     * Test attribute "downloadcount"
     */
    public function testPropertyDownloadcount()
    {
    }

    /**
     * Test attribute "viewsize"
     */
    public function testPropertyViewsize()
    {
    }

    /**
     * Test attribute "thumbsize"
     */
    public function testPropertyThumbsize()
    {
    }

    /**
     * Test attribute "allowpublicaccess"
     */
    public function testPropertyAllowpublicaccess()
    {
    }

    /**
     * Test attribute "allowpublicupload"
     */
    public function testPropertyAllowpublicupload()
    {
    }

    /**
     * Test attribute "allowpublicviewonly"
     */
    public function testPropertyAllowpublicviewonly()
    {
    }

    /**
     * Test attribute "allowpublicuploadonly"
     */
    public function testPropertyAllowpublicuploadonly()
    {
    }

    /**
     * Test attribute "isdir"
     */
    public function testPropertyIsdir()
    {
    }

    /**
     * Test attribute "isvalid"
     */
    public function testPropertyIsvalid()
    {
    }

    /**
     * Test attribute "createddate"
     */
    public function testPropertyCreateddate()
    {
    }

    /**
     * Test attribute "createdts"
     */
    public function testPropertyCreatedts()
    {
    }

    /**
     * Test attribute "allowedit"
     */
    public function testPropertyAllowedit()
    {
    }

    /**
     * Test attribute "allowdelete"
     */
    public function testPropertyAllowdelete()
    {
    }

    /**
     * Test attribute "allowsync"
     */
    public function testPropertyAllowsync()
    {
    }

    /**
     * Test attribute "allowshare"
     */
    public function testPropertyAllowshare()
    {
    }

    /**
     * Test attribute "shareowner"
     */
    public function testPropertyShareowner()
    {
    }

    /**
     * Test attribute "hidenotifications"
     */
    public function testPropertyHidenotifications()
    {
    }

    /**
     * Test attribute "ispublicsecure"
     */
    public function testPropertyIspublicsecure()
    {
    }

    /**
     * Test attribute "defaultfile"
     */
    public function testPropertyDefaultfile()
    {
    }

    /**
     * Test attribute "lastaccessdts"
     */
    public function testPropertyLastaccessdts()
    {
    }

    /**
     * Test attribute "lastaccess"
     */
    public function testPropertyLastaccess()
    {
    }

    /**
     * Test attribute "recentactivitycount"
     */
    public function testPropertyRecentactivitycount()
    {
    }
}
