<?php
/**
 * ProfileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FileCloud_User_API
 *
 * FileCloud HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProfileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for beginprofilecreation
     *
     * Profile_Related_API - beginprofilecreation is used to create a profile for user.
     *
     */
    public function testBeginprofilecreation()
    {
    }

    /**
     * Test case for changelanguage
     *
     * Profile_Related_API - changelanguage is used to change the language of FC system from the specified languages.
     *
     */
    public function testChangelanguage()
    {
    }

    /**
     * Test case for checkid
     *
     * Profile_Related_API - checkid is used to check if the mentioned username by the user is available or not in the FC system..
     *
     */
    public function testCheckid()
    {
    }

    /**
     * Test case for createprofile
     *
     * Profile_Related_API - createprofile is used to create an account for a new user.
     *
     */
    public function testCreateprofile()
    {
    }

    /**
     * Test case for getprofileimage
     *
     * Profile_Related_API - getprofileimage is used to see the profile image of the user in FC system..
     *
     */
    public function testGetprofileimage()
    {
    }

    /**
     * Test case for getprofilesettings
     *
     * Profile_Related_API - getprofilesettings is used to get the saved settings of a profile.
     *
     */
    public function testGetprofilesettings()
    {
    }

    /**
     * Test case for setdisplayname
     *
     * Profile_Related_API - setdisplayname is used to change display name of the user in settings.
     *
     */
    public function testSetdisplayname()
    {
    }

    /**
     * Test case for subscribe
     *
     * Profile_Related_API - subscribe is used to receive email about any notifications from the system.
     *
     */
    public function testSubscribe()
    {
    }

    /**
     * Test case for unsubscribe
     *
     * Profile_Related_API - unsubscribe is used to not get any email notification from the system.
     *
     */
    public function testUnsubscribe()
    {
    }

    /**
     * Test case for updatepassword
     *
     * Profile_Related_API - updatepassword is used to change the password of the user from their profile.
     *
     */
    public function testUpdatepassword()
    {
    }
}
